### ISSUE TITLE
请问下群主对chatgpt的看法

### ISSUE THREAD

**Issue by zxcvbnm3057** [jiaxiaogang/he4o#13]
退群好久了，已经找不到群号，吧里蹲了几天没有关于这个的帖子，只好来这问问群主对chatgpt的看法

**Comment by jiaxiaogang** [comment]
chatgpt挺好的,在大模型+现有各种AI成果的融合上,还大有可为,但chatgpt似乎自称并非agi系统什么的,所以虽挺好,但与我并非同行,不好公开评价;但听一个朋友说:

**Comment by jiaxiaogang** [comment]
接上: gpt是大模型+语义等成果+人工基础上的改进,它并不具备agi中大家普遍要求的那些能力,站在我自己的熵减机的角度,语言的熵比较明确 (输入时,一个概念可能较为明确的被几个字所指代,譬如,你看到一个苹果的样子形状色泽,然后气味,口味等),它们共同定义了苹果,而什么定义了形状色泽气味口味呢?又是更加微观的信息,)

而从文字出发,这整个从微观到宏观浮现定义的过程,就会简略的多,也更容易达成;这种短爽快的方式洽洽错过了agi中最重要的东西;

综上: 无论是对agi系统要求的整体度,还是内部对信息处理的细微过程,我认为gpt都是远远不够的,尽管它把认为容易体现出效果的那部分做出来,已经算最容易博得大众所认可,但越是有自己想法的同学,越难以被这一点刺激到g点

**Comment by zxcvbnm3057** [comment]
近期又遇到了一点疑问：是否gpt系列模型的效果可以验证在人工智能方面也可以“力大砖飞”呢，采用超大模型进行训练，根据神经网络基本原理可以知道网络层数和每层节点高到一定程度，总是可以拟合上任意给定函数。由此也应该能做到AGI的效果吧。退一步讲，着重模型深度和广度而非具体设计，在可预期未来是否会出现以力破巧的效果，即大模型先于特定设计小模型逼近广义AGI

**Comment by jiaxiaogang** [comment]
大模型只是个统计学加涌现的系统，它与智能有交集，但交集很小，别把它当agi看。不用回复我了，我对gpt没兴趣，尽管它很火。
